#include "batcher.h"
#include "heap.h"
#include "quick.h"
#include "set.h"
#include "shell.h"
#include "stats.h"

#include <getopt.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#define OPTIONS "ahbsqr:n:p:H"

//static function to print program usage
static void program_usage(void) {
    fprintf(stderr, "SYNOPSIS\n"
                    "   A collection of comparison-based sorting algorithms.\n\n"
                    "USAGE\n"
                    "   ./sorting [-Hasbhqn:p:r:] [-n length] [-p elements] [-r seed]\n\n"
                    "OPTIONS\n"
                    "  -H               Display program help and usage.\n"
                    "  -a               Enable all sorts.\n"
                    "  -s               Enable Shell Sort.\n"
                    "  -b               Enable Batcher Sort.\n"
                    "  -h               Enable Heap Sort.\n"
                    "  -q               Enable Quick Sort.\n"
                    "  -n length        Specify number of array elements (default: 100).\n"
                    "  -p elements      Specify number of elements to print (default: 100).\n"
                    "  -r seed          Specify random seed (default: 13371453).\n");
}

//static function to create a new array
static void create_array(uint32_t *arr, uint32_t size, uint32_t seed) {
    //the pseudorandom numbers generated by random() should be bit-masked to fit in 30 bits
    //use bit-wise AND operator
    srandom(seed); //generate array of pseudorandom numbers
    for (uint32_t i = 0; i < size; i++) {
        arr[i] = random() & ((1 << 30) - 1); //bit mask to fit in 30 bits
    }
}

//I used this function below to graph how my sortings algorithms performed when sorting an array in reverse order
/*
//create static void function that generates an array of numbers in reverse order
static void create_reverse_array(uint32_t *arr, uint32_t size, uint32_t seed) {
    srandom(seed); //generate array of pseudorandom numbers
    for (uint32_t i = 0; i < size; i++) {
        arr[i] = size - i; //Set the index of the array equal to the size of the array minus the index
    }
}
*/

int main(int argc, char **argv) {
    uint32_t seed = 13371453; //default seed
    uint32_t size = 100; //default size
    uint32_t elements = 100; //default elements
    int opt = 0; //initialize opt to 0
    uint32_t *random_array; //initialize random array
    enum sorts { SHELL, BATCHER, HEAP, QUICK }; //enumeration of
    char *sort_names[] = { "Shell", "Batcher", "Heap", "Quick" }; //char array of sort names
    Set s = set_empty(); //initialize set by emptying it
    Stats stats; //changed this from stat to stats
    while ((opt = getopt(argc, argv, OPTIONS)) != -1) {
        switch (opt) {
        case 'a':
            //employs all sorting algorithms
            s = set_insert(s, HEAP); //inserts heap sort
            s = set_insert(s, BATCHER); //inserts batcher sort
            s = set_insert(s, SHELL); //inserts shell sort
            s = set_insert(s, QUICK); //inserts quick sort
            break;
        case 'h':
            //enables heap sort
            s = set_insert(s, HEAP); //inserts heap sort
            break;
        case 'b':
            //enables batcher sort
            s = set_insert(s, BATCHER); //inserts batcher sort
            break;
        case 's':
            //enables shell sort
            s = set_insert(s, SHELL); //inserts shell sort
            break;
        case 'q':
            //enables quick sort
            s = set_insert(s, QUICK); //inserts quick sort
            break;
        case 'r':
            //set the random seed to seed
            seed = strtoul(optarg, NULL, 10); //get random seed from user input
            break;
        case 'n':
            //set the array size to size
            size = strtoul(optarg, NULL, 10); //get array size from user input
            break;
        case 'p':
            //print out elements number of elements from the arary
            elements = strtoul(optarg, NULL, 10); //get number of elements from user input
            break;
        case 'H':
            program_usage(); //call program_usage function
            return 0;
        default:
            program_usage(); //call program_usage function
            return 1;
        }
    }
    if (s == 0) {
        //print to stderr the line if no sorts were performed
        fprintf(stderr, "Select at least one sort to perform.\n");
        program_usage(); //call program_usage function
        return 1;
    }
    //if the number of elements to print is greater than the size of the array
    if (elements > size) {
        elements
            = size; //set elements to size because we can't print more elements than the size of the array
    }
    random_array = malloc(size * sizeof(uint32_t)); //allocate memory for random array
    for (uint32_t i = 0; i < 4; i++) {
        if (set_member(s, i)) { //if the set member is in the set
            reset(&stats); //reset the stats
            create_array(random_array, size, seed); //call create array function
            // create_reverse_array(random_array, size, seed); //call create reverse array function
            if (i == SHELL) {
                shell_sort(&stats, random_array, size); //call shell_sort function
            } else if (i == BATCHER) {
                batcher_sort(&stats, random_array, size); //call batcher_sort function
            } else if (i == HEAP) {
                heap_sort(&stats, random_array, size); //call heap_sort function
            } else if (i == QUICK) {
                quick_sort(&stats, random_array, size); //call quick_sort function
            }
            printf("%s Sort, %d elements, %lu moves, %lu compares\n", sort_names[i], size,
                stats.moves, stats.compares); //print statement for output
            for (uint32_t i = 0; i < elements; i++) {
                if (i % 5 == 0 && i != 0) { //print new line every 5 elements
                    printf("\n"); //print new line
                }
                printf("%13" PRIu32,
                    random_array[i]); //print each element in the sorted array with a width of 13
                if (i == elements - 1) { //if statment to print new line if elements is less than 5
                    printf("\n"); //print new line
                }
            }
        }
    }
    free(random_array); //free memory allocated for random_array
    return 0; //return 0 to indicate success execution of program
}
